/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JlptN3RouteImport } from './routes/jlpt-n3'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JlptN3Route = JlptN3RouteImport.update({
  id: '/jlpt-n3',
  path: '/jlpt-n3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/jlpt-n3': typeof JlptN3Route
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/jlpt-n3': typeof JlptN3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/jlpt-n3': typeof JlptN3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/jlpt-n3'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/jlpt-n3'
  id: '__root__' | '/home' | '/jlpt-n3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  JlptN3Route: typeof JlptN3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jlpt-n3': {
      id: '/jlpt-n3'
      path: '/jlpt-n3'
      fullPath: '/jlpt-n3'
      preLoaderRoute: typeof JlptN3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  JlptN3Route: JlptN3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
